<a href="https://colab.research.google.com/github/geniusrusho/Creating-the-Koch-curve---fractral-geometry/blob/main/Welcome_to_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Principle Component Analysis**

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eig
from numpy.linalg import eig



In [27]:
data=np.array([[3,4],[2,8],[6,9],[10,12]])

In [28]:
print(data)

[[ 3  4]
 [ 2  8]
 [ 6  9]
 [10 12]]


In [31]:
df=pd.DataFrame(data,columns=["ML","DL"])

In [32]:
df

ML  DL
0   3   4
1   2   8
2   6   9
3  10  12

In [36]:
plt.scatter(df["ML"],df["DL"])

In [37]:
data.T

array([[ 3,  2,  6, 10],
       [ 4,  8,  9, 12]])

In [40]:
np.mean(data.T,axis=1)

array([5.25, 8.25])

In [41]:
meanbycol=np.mean(data,axis=0)

In [49]:
scaled_data=data-meanbycol

In [45]:
print(3-5,25)

-2 25


In [51]:
cov_mat=np.cov(scaled_data.T)

In [53]:
eig_val,eig_vec=np.linalg.eig(cov_mat)

In [54]:
eig_vec

array([[ 0.74289445, -0.66940857],
       [ 0.66940857,  0.74289445]])

In [55]:
scaled_data

array([[-2.25, -4.25],
       [-3.25, -0.25],
       [ 0.75,  0.75],
       [ 4.75,  3.75]])

In [57]:
eig_vec.T.dot(scaled_data.T).T

array([[-4.51649894, -1.65113213],
       [-2.58175911,  1.98985424],
       [ 1.05922727,  0.05511441],
       [ 6.03903078, -0.39383652]])

In [58]:
from sklearn.decomposition import PCA

In [59]:
pca=PCA()

In [60]:
pca.fit_transform(scaled_data)

array([[-4.51649894, -1.65113213],
       [-2.58175911,  1.98985424],
       [ 1.05922727,  0.05511441],
       [ 6.03903078, -0.39383652]])

In [62]:
pd.DataFrame(data=pca.fit_transform(scaled_data),columns=["PC1","PC2"])

PC1       PC2
0 -4.516499 -1.651132
1 -2.581759  1.989854
2  1.059227  0.055114
3  6.039031 -0.393837

In [64]:
pca.inverse_transform(pca.fit_transform(scaled_data))

array([[-2.25, -4.25],
       [-3.25, -0.25],
       [ 0.75,  0.75],
       [ 4.75,  3.75]])

In [65]:
scaled_data

array([[-2.25, -4.25],
       [-3.25, -0.25],
       [ 0.75,  0.75],
       [ 4.75,  3.75]])

In [66]:
pca.explained_variance_ratio_

array([0.90428109, 0.09571891])

In [98]:
new_data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/glass/glass.data").head()